### PR TITLE
feat(mint): take input hashes belonging to mint, in reissue method

### PR DESCRIPTION
**Pull request by oetyng**
- Add custom error for validation that the filtered input actually is present in the transaction as well.

### CODE REVIEW

**Review by davidrusu — DISMISSED** [review]
Looks good :ship:

**Comment by davidrusu** [comment]
@dan-da did this work get merged? I'm not seeing the commit on master

**Comment by dan-da** [comment]
weird, I only merged #26 and then deleted the branch as usual.  It seems that this PR was into that same branch, so it closed this one.  Let's see what we can do...

**Comment by dan-da** [comment]
ok, I restored the branch and reopened this.

**Pull request closed without merging**
